Move NGX_HTTP_SSL check to the config script.

diff --git a/config b/config
--- a/config
+++ b/config
@@ -1,3 +1,9 @@
+if [ $HTTP != YES ] || [ $HTTP_SSL != YES ]; then
+    echo
+    echo "$0: error: nginx-ct requires --with_http_ssl_module to be set"
+    exit 1
+fi
+
 ngx_addon_name=ngx_http_ssl_ct_module
 HTTP_MODULES="$HTTP_MODULES ngx_http_ssl_ct_module"
 NGX_ADDON_SRCS="$NGX_ADDON_SRCS $ngx_addon_dir/ngx_http_ssl_ct_module.c"
